stages:
    - pre-compile
    - compile
    - deploy
    - test
    - undeploy
    - clean
    - cleanup-docker-registry
    - cleanup-build-cache
.PreCompile: &JobPreCompile
    image: docker.iondv.ru/kube/docker/mocha
    type: pre-compile
    except:
      - schedules
    tags:
        - dapp
    script:
        - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/pre-compile.sh | bash
    artifacts:
        name: "$CI_JOB_STAGE_$CI_BUILD_REF_NAME"
        expire_in: 6 mos
        when: on_success
        paths:
           - Dappfile
    when: manual
    allow_failure: false
.Compile: &JobCompile
    type: compile
    except:
      - schedules
    tags:
        - dapp
    script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/compile_with_dapp_stages.sh | bash
    allow_failure: false
    #when: manual
.Deploy: &JobDeploy
  type: deploy
  except:
    - schedules
  tags:
    - kube-deploy
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/deploy_review_on_kube.sh | bash
  after_script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/after_deploy.sh | bash
  variables:
    GIT_STRATEGY: none
    NAMESPACE: "review"
  when: on_success
.Test: &JobTest
    image: docker.iondv.ru/kube/docker/protractor
    type: test
    except:
      - schedules
    tags:
        - testing
    script:
        - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/test_protractor.sh | bash
    variables:
        TEST_SELENIUM_ADDR: "selenium-hub.kube.local"
        TEST_SELENIUM_PORT: 80
        ION_TEST_LOGIN: "user"
        ION_TEST_PASSWORD: "${userpassword}"
        ION_TEST_URL: "http://${CI_COMMIT_REF_SLUG}.${CI_PROJECT_NAME}.kube.local"
    allow_failure: false
    when: on_success
.BackendTest: &BackendTest
    type: test
    except:
      - schedules
    tags:
        - kube-deploy
    script:
        - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/test_backend.sh | bash
    allow_failure: false
#Builds on platform
Pre-Compile:
    <<: *JobPreCompile
    only:
      - /^[A-Z]+-\d+$/
      - /^v\d+\.\d+$/
      - web
Compile:
  <<: *JobCompile
  only:
      - /^[A-Z]+-\d+$/
      - /^v\d+\.\d+$/
      - web
  dependencies:
    - Pre-Compile
Deploy review:
  <<: *JobDeploy
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CI_COMMIT_REF_SLUG}.${CI_PROJECT_NAME}.kube.local
    on_stop: stop_review
  only:
      - /^[A-Z]+-\d+$/
      - /^v\d+\.\d+$/
      - web
stop_review:
  type: undeploy
  except:
    - schedules
  tags:
    - kube-deploy
  variables:
    GIT_STRATEGY: none
    NAMESPACE: review
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/undeploy_review.sh | bash
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  only:
      - /^[A-Z]+-\d+$/
      - /^v\d+\.\d+$/
      - web
### TEST SECITONS
.Testing Review:
    <<: *JobTest
    only:
      - /^[A-Z]+-\d+$/
      - /^v\d+\.\d+$/
      - web
    except:
      - schedules
    allow_failure: true
.ion-workflow:
    tags:
        - kube-deploy
    except:
      - schedules
    script:
        - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/test_ion_workflow.sh | bash
    only:
      - /^[A-Z]+-\d+$/
      - /^v\d+\.\d+$/
      - web
### START PRODUCTION
Pre-Compile_production:
    <<: *JobPreCompile
    only:
        - tags
Compile production:
  <<: *JobCompile
  only:
    - tags
  variables:
    NAMESPACE: "production"
    CI_COMMIT_REF_SLUG: "production"
  before_script:
    - curl -fsSL https://git.iondv.ru/ION/functional_tests/raw/master/stage_access.py | python
  dependencies:
   - Pre-Compile_production
Tag review:
  <<: *JobDeploy
  tags:
    - kube-deploy
  variables:
    NAMESPACE: "review"
  only:
    - tags
  before_script:
    - curl -fsSL https://git.iondv.ru/ION/functional_tests/raw/master/stage_access.py | python
  environment:
    name: Tag Review
    url: http://${CI_COMMIT_REF_SLUG}.${CI_PROJECT_NAME}.kube.local
production:
  <<: *JobDeploy
  tags:
    - kube-deploy
  variables:
    NAMESPACE: "production"
    CI_COMMIT_REF_SLUG: "production"
    MEM_LIMIT: "256Mi"
  only:
    - tags
  before_script:
    - curl -fsSL https://git.iondv.ru/ION/functional_tests/raw/master/stage_access.py | python
  environment:
    name: Production
    url: http://${CI_COMMIT_REF_SLUG}.${CI_PROJECT_NAME}.kube.local
  when: manual
  allow_failure: true
### END PRODUCTION
### CLEAN SECTION
Clean:
  type: clean
  tags:
    - dapp
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/drop_dapp.sh | bash
  when: manual
  only:
    - web
  except:
    - tags
  before_script:
    - curl -fsSL https://git.iondv.ru/ION/functional_tests/raw/master/stage_access.py | python
  ### DAPP CleanAPP
Cleanup docker registry:
  stage: cleanup-docker-registry
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/cleanup_docker_registry.sh | bash
  retry: 2
  only:
    - schedules
  tags:
    - kube-deploy
Cleanup build cache:
  stage: cleanup-build-cache
  script:
    - curl -fsSL https://git.iondv.ru/kube/stages/raw/master/cleanup_build_cache.sh | bash
  retry: 2
  only:
    - schedules
  tags:
    - kube-deploy
